[input]
base_directory = "pages"
files = []

[output]
filename = "/Users/rootulp/git/rootulp/portfolio/public/index-default.st"
excerpts_per_result = 1
[output]
filename = "/Users/rootulp/git/rootulp/portfolio/public/index-default.st"
excerpts_per_result = 1
